# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RestoFinder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RestoFinder
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod 'RealmSwift'

  target 'RestoFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RestoFinderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
